import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-matrix-dark text-matrix-green">
      <body className="min-h-screen">
        <nav className="bg-matrix-gray p-4 border-b border-matrix-green">
          <div className="container mx-auto flex justify-center items-center space-x-8">
            <a href="/" className="text-2xl font-bold">
              Hammad Nawaz
            </a>
            <div className="space-x-4">
              <a href="/about" className="hover:underline">
                About
              </a>
              <a href="/projects" className="hover:underline">
                Projects
              </a>
              <a href="/contact" className="hover:underline">
                Contact
              </a>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}